start_frame: start
grid_topic: /semantic_map/grid
homes_topic: /semantic_map/homes
pucks_topic: /semantic_map/pucks

startup_homes_topic: /startup_survey/homes_start
startup_pucks_topic: /startup_survey/pucks_start
dynamic_pucks_topic: /puck/tracks_start

resolution: 0.05
rect_x_min: -0.5
rect_x_max: 5.5
rect_y_min: -0.5
rect_y_max: 4.5

wall_thickness_m: 0.12
home_radius_m: 0.12
puck_radius_m: 0.06

wall_value: 100
home_value: 100
puck_value: 80

use_dynamic_puck_tracks: true
allowed_puck_states: [DETECTED, RESERVED, PICKED]
publish_rate_hz: 1.0
